// src/components/WebsiteCard.tsx
import React, { useState } from 'react';
import { ExternalLink, Expand, Calendar, User } from 'lucide-react';

export interface Website {
  name: string;
  url: string;
  icon_url?: string;
  screenshot_url?: string;
  tags_list: string[];
  description: string;
  added_at: string;
  added_by: {
    user_alias: string;
    user_link: string;
  };
  sources: Array<{
    source_url: string;
    url_metadata: {
      og_title: string;
      og_description: string;
      og_image?: string;
    };
  }>;
}

interface WebsiteCardProps {
  website: Website;
  onExpand: (website: Website) => void;
  onTagClick: (tag: string) => void;
}

export const WebsiteCard: React.FC<WebsiteCardProps> = ({ website, onExpand, onTagClick }) => {
  const [imageLoaded, setImageLoaded] = useState(false);
  const [imageError, setImageError] = useState(false);

  const handleCardClick = (e: React.MouseEvent) => {
    if ((e.target as HTMLElement).closest('[data-prevent-card-click]')) {
      return;
    }
    window.open(website.url, '_blank', 'noopener,noreferrer');
  };

  const handleExpandClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    onExpand(website);
  };

  const handleTagClick = (e: React.MouseEvent, tag: string) => {
    e.stopPropagation();
    onTagClick(tag);
  };

  const displayImage = website.screenshot_url || website.icon_url;

  return (
    <div
      className="group bg-gray-900/30 backdrop-blur-sm border border-gray-700/50 rounded-xl overflow-hidden hover:border-orange-400/50 hover:bg-gray-900/50 transition-all duration-300 cursor-pointer hover:scale-[1.02] hover:shadow-xl hover:shadow-orange-400/10"
      onClick={handleCardClick}
      role="button"
      tabIndex={0}
      aria-label={`Visit ${website.name}`}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          handleCardClick(e);
        }
      }}
    >
      {/* Image Section */}
      <div className="relative h-48 bg-gradient-to-br from-gray-800 to-gray-900 overflow-hidden">
        {displayImage && !imageError ? (
          <>
            <img
              src={displayImage}
              alt={`${website.name} screenshot`}
              className={`w-full h-full object-cover transition-all duration-500 group-hover:scale-110 ${
                imageLoaded ? 'opacity-100' : 'opacity-0'
              }`}
              onLoad={() => setImageLoaded(true)}
              onError={() => setImageError(true)}
              loading="lazy"
            />
            {!imageLoaded && (
              <div className="absolute inset-0 bg-gradient-to-br from-amber-400/20 to-orange-500/20 animate-pulse"></div>
            )}
          </>
        ) : (
          <div className="absolute inset-0 bg-gradient-to-br from-orange-400/20 to-red-500/20 flex items-center justify-center">
            <ExternalLink className="w-12 h-12 text-orange-400/60" />
          </div>
        )}
        
        <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
        
        <button
          onClick={handleExpandClick}
          className="absolute top-3 right-3 bg-black/50 backdrop-blur-sm text-white p-2 rounded-lg opacity-0 group-hover:opacity-100 transition-all duration-200 hover:bg-orange-400/20 hover:text-orange-400"
          data-prevent-card-click
          aria-label="Expand details"
        >
          <Expand className="w-4 h-4" />
        </button>
      </div>

      {/* Content Section */}
      <div className="p-6 space-y-4">
        <div className="space-y-2">
          <h3 className="text-xl font-bold text-white group-hover:text-orange-400 transition-colors duration-200 line-clamp-1">
            {website.name}
          </h3>
          <p className="text-gray-300 text-sm line-clamp-2 leading-relaxed">
            {website.description}
          </p>
        </div>

        {/* Tags */}
        <div className="flex flex-wrap gap-2">
          {website.tags_list.slice(0, 3).map((tag, index) => (
            <button
              key={index}
              onClick={(e) => handleTagClick(e, tag)}
              className="px-3 py-1 bg-orange-400/10 border border-orange-400/20 text-orange-400 text-xs rounded-full hover:bg-orange-400/20 hover:border-orange-400/40 transition-all duration-200"
              data-prevent-card-click
              aria-label={`Filter by ${tag}`}
            >
              {tag}
            </button>
          ))}
          {website.tags_list.length > 3 && (
            <span className="px-3 py-1 bg-gray-700/30 text-gray-400 text-xs rounded-full">
              +{website.tags_list.length - 3}
            </span>
          )}
        </div>

        {/* Metadata */}
        <div className="flex items-center justify-between text-xs text-gray-400 pt-2 border-t border-gray-700/30">
          <div className="flex items-center space-x-2">
            <Calendar className="w-3 h-3" />
            <span>{new Date(website.added_at).toLocaleDateString()}</span>
          </div>
          <div className="flex items-center space-x-2">
            <User className="w-3 h-3" />
            <span className="truncate max-w-20">{website.added_by.user_alias}</span>
          </div>
        </div>
      </div>
    </div>
  );
};

// src/app/shared/components/website-card.component.ts
import { Component, ChangeDetectionStrategy, input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Website } from '../models/database.types';

@Component({
  selector: 'app-website-card',
  imports: [RouterLink],
  template: `
    <article
      class="bg-zinc-900 rounded-lg shadow-lg hover:shadow-orange-600/30 hover:shadow-xl transition-all duration-200 group overflow-hidden"
      role="article"
    >
      <!-- Logo Section -->
      <div
        class="relative h-32 bg-gradient-to-br from-zinc-700 to-zinc-800 flex items-center justify-center"
      >
        @if (website().logo_url) {
        <img
          [src]="website().logo_url"
          [alt]="website().name + ' logo'"
          class="w-auto h-auto object-contain"
          loading="lazy"
        />
        } @else {
        <div
          class="w-16 h-16 bg-gradient-to-br from-zinc-600 to-zinc-700 rounded-lg flex items-center justify-center"
          aria-hidden="true"
        >
          <svg class="w-8 h-8 text-zinc-400" fill="currentColor" viewBox="0 0 20 20">
            <path
              fill-rule="evenodd"
              d="M4.083 9h1.946c.089-1.546.383-2.97.837-4.118A6.004 6.004 0 004.083 9zM10 2a8 8 0 100 16 8 8 0 000-16zm0 2c-.076 0-.232.032-.465.262-.238.234-.497.623-.737 1.182-.389.907-.673 2.142-.766 3.556h3.936c-.093-1.414-.377-2.649-.766-3.556-.24-.56-.5-.948-.737-1.182C10.232 4.032 10.076 4 10 4zm3.971 5c-.089-1.546-.383-2.97-.837-4.118A6.004 6.004 0 0115.917 9h-1.946zm-2.003 2H8.032c.093 1.414.377 2.649.766 3.556.24.56.5.948.737 1.182.233.23.389.262.465.262.076 0 .232-.032.465-.262.238-.234.498-.623.737-1.182.389-.907.673-2.142.766-3.556zm1.166 4.118c.454-1.147.748-2.572.837-4.118h1.946a6.004 6.004 0 01-2.783 4.118zm-6.268 0C6.412 13.97 6.118 12.546 6.03 11H4.083a6.004 6.004 0 002.783 4.118z"
              clip-rule="evenodd"
            ></path>
          </svg>
        </div>
        }
      </div>

      <!-- Content Section -->
      <div class="p-4">
        <!-- Website Name -->
        <a
          [routerLink]="['/website', encodeWebsiteName(website().name)]"
          class="block group-hover:text-orange-400 transition-colors focus:outline-none focus:ring-2 focus:ring-orange-400 focus:ring-offset-2 focus:ring-offset-zinc-800 rounded"
          [attr.aria-label]="'View details for ' + website().name"
        >
          <h3 class="text-lg font-semibold text-white mb-2 truncate">
            {{ website().name }}
          </h3>
        </a>

        <!-- Description -->
        <p class="text-zinc-300 text-sm mb-3 line-clamp-2" [attr.title]="website().description">
          {{ website().description }}
        </p>

        <!-- Tags -->
        @if (website().tags && website().tags!.length > 0) {
        <div class="flex flex-wrap gap-2 mb-3" role="list" aria-label="Website tags">
          @for (tag of website().tags; track tag.id) {
          <a
            [routerLink]="['/search']"
            [queryParams]="{ tag: tag.slug }"
            class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-orange-400/10 text-orange-400 border border-orange-400/20 hover:bg-orange-400/20 transition-colors focus:outline-none focus:ring-2 focus:ring-orange-400 focus:ring-offset-2 focus:ring-offset-zinc-800"
            role="listitem"
            [attr.aria-label]="'Filter websites by ' + tag.name + ' tag'"
          >
            {{ tag.name }}
          </a>
          }
        </div>
        }

        <!-- Actions -->
        <div class="flex items-center justify-between pt-2 border-t border-zinc-700">
          <a
            [href]="website().url"
            target="_blank"
            rel="noopener"
            class="inline-flex items-center px-3 py-2 text-sm text-white bg-orange-500 hover:bg-orange-600 rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-orange-400 focus:ring-offset-2 focus:ring-offset-zinc-800"
            [attr.aria-label]="'Visit ' + website().name + ' website (opens in new tab)'"
          >
            <svg class="w-4 h-4 mr-1" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true">
              <path
                d="M11 3a1 1 0 100 2h2.586l-6.293 6.293a1 1 0 101.414 1.414L15 6.414V9a1 1 0 102 0V4a1 1 0 00-1-1h-5z"
              ></path>
              <path
                d="M5 5a2 2 0 00-2 2v8a2 2 0 002 2h8a2 2 0 002-2v-3a1 1 0 10-2 0v3H5V7h3a1 1 0 000-2H5z"
              ></path>
            </svg>
            Visit
          </a>

          <div class="text-right">
            <time
              class="text-xs text-zinc-500 block"
              [attr.datetime]="website().created_at"
              [attr.title]="'Added on ' + formatDate(website().created_at)"
            >
              {{ formatDate(website().created_at) }}
            </time>
            @if (website().author) {
            <div
              class="text-xs text-zinc-500 mt-1"
              [attr.title]="'Added by ' + website().author!.display_name"
            >
              by {{ website().author!.display_name }}
            </div>
            }
          </div>
        </div>
      </div>
    </article>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class WebsiteCardComponent {
  website = input.required<Website>();

  formatDate(dateString: string): string {
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  }

  encodeWebsiteName(name: string): string {
    return encodeURIComponent(name);
  }
}
